/*
 * main.c - GSURF executable entry point
 *
 * Copyright (C) 2026 Zach Podbielniak
 * SPDX-License-Identifier: AGPL-3.0-or-later
 *
 * Thin binary: option parsing, config loading, and the main loop. All
 * browser logic lives in libgsurf so other applications can embed it.
 */

#include "gsurf.h"

#include <gdk/gdk.h>
#include <gdk/gdkkeysyms.h>
#include <stdlib.h>
#include <string.h>

/* Embedded default YAML + C config (generated by the build from
 * data/default-config.yaml and data/default-config.c). */
#include "gsurf-default-config.h"

#ifdef GSURF_HAVE_LRG_BACKEND
#include "backend/lrg/gsurf-lrg-window.h"
#endif

/* ===== CLI options ===== */

static gchar    *opt_config = NULL;
static gchar    *opt_c_config = NULL;
static gboolean  opt_version = FALSE;
static gboolean  opt_no_yaml = FALSE;
static gboolean  opt_no_c_config = FALSE;
static gboolean  opt_no_modules = FALSE;
static gboolean  opt_generate_yaml = FALSE;
static gboolean  opt_generate_c = FALSE;
static gboolean  opt_list_modules = FALSE;
static gboolean  opt_fullscreen = FALSE;

/* --lrg[=MODE]: use the libregnum/raylib backend.  Bare --lrg means 2D
 * (matching `emacs --lrg').  Parsed by opt_lrg_cb so the value is optional. */
static gboolean            opt_lrg_given = FALSE;
static GsurfLrgRenderMode  opt_lrg_mode  = GSURF_LRG_RENDER_MODE_2D;

static gboolean
opt_lrg_cb(const gchar *name, const gchar *value, gpointer data, GError **error)
{
	(void) name;
	(void) data;
	opt_lrg_given = TRUE;
	/* gsurf_lrg_render_mode_from_string accepts NULL/"" as 2D. */
	if (!gsurf_lrg_render_mode_from_string(value, &opt_lrg_mode)) {
		g_set_error(error, G_OPTION_ERROR, G_OPTION_ERROR_BAD_VALUE,
			"unknown --lrg mode '%s' (use 2d, 3d, or 3dvr)", value);
		return FALSE;
	}
	return TRUE;
}

static const GOptionEntry entries[] = {
	{ "config", 'c', 0, G_OPTION_ARG_FILENAME, &opt_config,
	  "Use the specified YAML config file", "PATH" },
	{ "c-config", 0, 0, G_OPTION_ARG_FILENAME, &opt_c_config,
	  "Use the specified C config file", "PATH" },
	{ "no-yaml-config", 0, 0, G_OPTION_ARG_NONE, &opt_no_yaml,
	  "Skip YAML config loading (use built-in defaults)", NULL },
	{ "no-c-config", 0, 0, G_OPTION_ARG_NONE, &opt_no_c_config,
	  "Skip C config compilation and loading", NULL },
	{ "no-modules", 0, 0, G_OPTION_ARG_NONE, &opt_no_modules,
	  "Do not load any modules", NULL },
	{ "generate-yaml-config", 0, 0, G_OPTION_ARG_NONE, &opt_generate_yaml,
	  "Print the default YAML config to stdout and exit", NULL },
	{ "generate-c-config", 0, 0, G_OPTION_ARG_NONE, &opt_generate_c,
	  "Print the default C config to stdout and exit", NULL },
	{ "list-modules", 0, 0, G_OPTION_ARG_NONE, &opt_list_modules,
	  "List available modules and exit", NULL },
	{ "fullscreen", 'f', 0, G_OPTION_ARG_NONE, &opt_fullscreen,
	  "Start in fullscreen", NULL },
	{ "lrg", 0, G_OPTION_FLAG_OPTIONAL_ARG, G_OPTION_ARG_CALLBACK,
	  (gpointer) opt_lrg_cb,
	  "Use the libregnum/raylib backend in a raylib window "
	  "(MODE: 2d [default], 3d/3dvr reserved)", "MODE" },
	{ "version", 'v', 0, G_OPTION_ARG_NONE, &opt_version,
	  "Show version and exit", NULL },
	{ NULL }
};

/* ===== Built-in module registry (drives --list-modules) ===== */

typedef struct {
	const gchar *name;
	const gchar *description;
} GsurfBuiltinModule;

static const GsurfBuiltinModule builtin_modules[] = {
	{ "search_engines", "Prefix-based search engines with default-engine fallback" },
	{ "chromebar",      "Address bar that falls back to search for non-URI input" },
	{ "history",        "Log visited URIs to a history file (dmenu integration)" },
	{ "homepage",       "Startup/new-view page and go-home keybind" },
	{ "toggles",        "Runtime toggle keybinds for JS, images, TLS, dark mode, etc." },
	{ "adblock",        "Host/pattern-based request blocking (EasyList + hosts files)" },
	{ "cookie_policy",  "Cookie accept policy with an @Aa-style cycle toggle" },
	{ "tabs",           "Tab-bar UI over the view stack with new/close/switch keys" },
	{ "find_bar",       "Find-in-page UI over the engine find controller" },
	{ "modal",          "Vim-like modal input and link hinting (vimium-style 'f')" },
	{ "omnibar",        "Frequency/recency-ranked history completion popup" },
	{ "bookmarks",      "Save and recall bookmarks (dmenu or built-in popup)" },
	{ "externalpipe",   "Pipe page HTML/text/selection to external commands" },
	{ "playexternal",   "Send media/page/link URI to an external player (mpv)" },
	{ "downloads",      "Download manager list UI with progress and notifications" },
	{ "userscripts",    "Inject global and per-domain user JavaScript" },
	{ "site_styles",    "Per-URI user CSS stylesheets (surf styles[])" },
	{ "uri_params",     "Per-domain web engine setting overrides (surf uriparams[])" },
	{ "cert_manager",   "Per-domain certificate exceptions and pinning" },
	{ "useragent",      "Dynamic and per-domain user-agent switching" },
	{ "notifications",  "Desktop notifications (downloads, Web Notifications)" },
	{ "mcp",            "MCP server for AI assistant integration (requires MCP=1)" },
	{ "inspector",      "Toggle the web inspector / devtools" },
	{ "spacesearch",    "Leading space in the bar forces a search" },
	{ "dark_mode",      "Force dark color scheme with optional dark user CSS" },
	{ "status_bar",     "Bottom status bar: URI, load progress, TLS, mode" },
	{ "geolocation",    "Fine-grained geolocation permission policy per-site" },
	{ "session",        "Save and restore open views (tab sessions)" },
	{ "proxy_switch",   "Cycle through proxy presets at runtime" },
	{ NULL, NULL }
};

static void
print_module_list(void)
{
	gint i;

	g_print("Available gsurf modules:\n\n");
	g_print("  %-16s %s\n", "MODULE", "DESCRIPTION");
	g_print("  %-16s %s\n", "------", "-----------");
	for (i = 0; builtin_modules[i].name != NULL; i++)
		g_print("  %-16s %s\n", builtin_modules[i].name,
			builtin_modules[i].description);
	g_print("\nEnable modules under the `modules:` section of your config.yaml.\n");
}

/* ===== Keybinding dispatch ===== */

/* Forward declarations (definitions appear later in the file). */
static void       load_uri_rewritten(GsurfView *view, const gchar *input);
static void       setup_view(GsurfApplication *app, GsurfWindow *window, GsurfView *view);
static GsurfView *make_tab(GsurfWindow *window, const gchar *uri);

static void
scroll_js(GsurfView *view, const gchar *js)
{
	gsurf_view_run_javascript_async(view, js, NULL, NULL, NULL);
}

static gboolean
execute_action(GsurfApplication *app, GsurfWindow *window,
               GsurfView *view, GsurfAction action)
{
	if (view == NULL)
		return FALSE;

	switch (action) {
	case GSURF_ACTION_BACK:           gsurf_view_go_back(view); return TRUE;
	case GSURF_ACTION_FORWARD:        gsurf_view_go_forward(view); return TRUE;
	case GSURF_ACTION_RELOAD:         gsurf_view_reload(view, FALSE); return TRUE;
	case GSURF_ACTION_RELOAD_NOCACHE: gsurf_view_reload(view, TRUE); return TRUE;
	case GSURF_ACTION_STOP:           gsurf_view_stop_loading(view); return TRUE;
	case GSURF_ACTION_ZOOM_IN:
		gsurf_view_set_zoom_level(view, gsurf_view_get_zoom_level(view) + 0.1);
		return TRUE;
	case GSURF_ACTION_ZOOM_OUT:
		gsurf_view_set_zoom_level(view, MAX(0.2, gsurf_view_get_zoom_level(view) - 0.1));
		return TRUE;
	case GSURF_ACTION_ZOOM_RESET:     gsurf_view_set_zoom_level(view, 1.0); return TRUE;
	case GSURF_ACTION_SCROLL_DOWN:    scroll_js(view, "window.scrollBy(0,60)"); return TRUE;
	case GSURF_ACTION_SCROLL_UP:      scroll_js(view, "window.scrollBy(0,-60)"); return TRUE;
	case GSURF_ACTION_SCROLL_LEFT:    scroll_js(view, "window.scrollBy(-60,0)"); return TRUE;
	case GSURF_ACTION_SCROLL_RIGHT:   scroll_js(view, "window.scrollBy(60,0)"); return TRUE;
	case GSURF_ACTION_SCROLL_TOP:     scroll_js(view, "window.scrollTo(0,0)"); return TRUE;
	case GSURF_ACTION_SCROLL_BOTTOM:  scroll_js(view, "window.scrollTo(0,document.body.scrollHeight)"); return TRUE;
	case GSURF_ACTION_PAGE_DOWN:      scroll_js(view, "window.scrollBy(0,window.innerHeight*0.9)"); return TRUE;
	case GSURF_ACTION_PAGE_UP:        scroll_js(view, "window.scrollBy(0,-window.innerHeight*0.9)"); return TRUE;
	case GSURF_ACTION_HALF_PAGE_DOWN: scroll_js(view, "window.scrollBy(0,window.innerHeight*0.5)"); return TRUE;
	case GSURF_ACTION_HALF_PAGE_UP:   scroll_js(view, "window.scrollBy(0,-window.innerHeight*0.5)"); return TRUE;
	case GSURF_ACTION_FIND_NEXT:      gsurf_view_find_next(view); return TRUE;
	case GSURF_ACTION_FIND_PREV:      gsurf_view_find_previous(view); return TRUE;
	case GSURF_ACTION_COPY_URL:       gsurf_view_copy_uri(view); return TRUE;
	case GSURF_ACTION_PASTE_URL: {
		g_autofree gchar *text = gsurf_view_read_clipboard_text(view);
		if (text != NULL && *text != '\0')
			load_uri_rewritten(view, text);
		return TRUE;
	}
	case GSURF_ACTION_HOME: {
		GsurfConfig *cfg = gsurf_config_get_default();
		if (cfg != NULL && cfg->homepage != NULL)
			load_uri_rewritten(view, cfg->homepage);
		return TRUE;
	}
	case GSURF_ACTION_OPEN_NEW_VIEW: {
		GsurfConfig *cfg = gsurf_config_get_default();
		const gchar *hovered = gsurf_view_get_hovered_uri(view);
		const gchar *uri = (hovered != NULL && *hovered != '\0')
			? hovered : (cfg != NULL ? cfg->new_view_uri : NULL);
		make_tab(window, uri);
		return TRUE;
	}
	case GSURF_ACTION_TOGGLE_FULLSCREEN:
		gsurf_window_set_fullscreen(window, !gsurf_window_get_fullscreen(window));
		return TRUE;
	case GSURF_ACTION_QUIT:           gsurf_application_quit(app); return TRUE;
	case GSURF_ACTION_OPEN_PROMPT:
#ifdef GSURF_HAVE_LRG_BACKEND
		/* Under --lrg the GTK chromebar/omnibar can't render, so the LRG
		 * window draws its own address bar.  On GTK, fall through so the
		 * chromebar/omnibar module handles the prompt. */
		if (GSURF_IS_LRG_WINDOW(window)) {
			gsurf_lrg_window_begin_url_edit(GSURF_LRG_WINDOW(window));
			return TRUE;
		}
#endif
		return FALSE;
	default:                          return FALSE;
	}
}

static gboolean
on_key_press(GsurfWindow *window, guint keyval, guint keycode, guint state,
             gpointer user_data)
{
	GsurfApplication *app = user_data;
	GsurfConfig *config = gsurf_application_get_config(app);
	GsurfModuleManager *mgr = gsurf_module_manager_get_default();
	GsurfView *view = gsurf_window_get_active_view(window);
	gboolean has_mod = (state & (GSURF_MOD_CTRL | GSURF_MOD_ALT | GSURF_MOD_SUPER)) != 0;
	gboolean is_escape = (keyval == GDK_KEY_Escape);
	g_autofree gchar *keystr = NULL;
	GsurfAction action;

	/* While the user is typing — a DOM editable element is focused, or the
	 * modal module is in INSERT passthrough — bare keys must reach the page
	 * and not be consumed by any module (e.g. find-bar's n/N) or core
	 * keybind. Modified keys and Escape still pass through (shortcuts; exit
	 * insert / blur). */
	if ((gsurf_module_manager_get_input_passthrough(mgr) ||
	     (view != NULL && gsurf_view_get_editing(view))) &&
	    !has_mod && !is_escape)
		return FALSE;

	/* Modules (modal keymap, hints, tabs) get first crack. */
	if (gsurf_module_manager_dispatch_key_event(mgr, view, keyval, keycode,
			state, GSURF_MODE_NORMAL))
		return TRUE;

	keystr = gsurf_keys_to_string(keyval, state);
	if (keystr == NULL)
		return FALSE;

	action = gsurf_config_get_keybind_action(config, keystr);
	if (action == GSURF_ACTION_NONE)
		return FALSE;

	return execute_action(app, window, view, action);
}

/* Build a normalized mousebind string ("Ctrl+Button2", "Button8", …) to
 * match the keys in the config `mousebinds:` map. */
static gchar *
mousebind_to_string(guint button, guint state)
{
	GString *s = g_string_new(NULL);

	if (state & GSURF_MOD_CTRL)  g_string_append(s, "Ctrl+");
	if (state & GSURF_MOD_ALT)   g_string_append(s, "Alt+");
	if (state & GSURF_MOD_SHIFT) g_string_append(s, "Shift+");
	if (state & GSURF_MOD_SUPER) g_string_append(s, "Super+");
	g_string_append_printf(s, "Button%u", button);

	return g_string_free(s, FALSE);
}

static gboolean
on_button_press(GsurfWindow *window, guint button, guint state, gpointer user_data)
{
	GsurfApplication *app = user_data;
	GsurfConfig *config = gsurf_application_get_config(app);
	GsurfModuleManager *mgr = gsurf_module_manager_get_default();
	GsurfView *view = gsurf_window_get_active_view(window);
	g_autofree gchar *binding = NULL;
	GsurfAction action;

	/* Modules get first crack at the raw button. */
	if (gsurf_module_manager_dispatch_mouse_event(mgr, view, button, state))
		return TRUE;

	binding = mousebind_to_string(button, state);
	action = gsurf_config_get_mousebind_action(config, binding);
	if (action == GSURF_ACTION_NONE)
		return FALSE;

	/* Mouse "open in new view" (middle-click / Ctrl-click) only fires over a
	 * hovered link. Off a link we pass through so the engine keeps native
	 * middle-click behavior (paste / autoscroll). */
	if (action == GSURF_ACTION_OPEN_NEW_VIEW) {
		const gchar *hovered = (view != NULL) ? gsurf_view_get_hovered_uri(view) : NULL;
		if (hovered == NULL || *hovered == '\0')
			return FALSE;
		make_tab(window, hovered);
		return TRUE;
	}

	return execute_action(app, window, view, action);
}

static void
on_view_load_changed(GsurfView *view, GsurfLoadEvent event, gpointer user_data)
{
	GsurfModuleManager *mgr = gsurf_module_manager_get_default();

	gsurf_module_manager_dispatch_load_changed(mgr, view, event);
	if (event == GSURF_LOAD_COMMITTED)
		gsurf_module_manager_dispatch_after_navigate(mgr, view,
			gsurf_view_get_uri(view));
}

/* Load a URI, first giving URI-handler modules (search engines, etc.) a
 * chance to rewrite the input. */
static void
load_uri_rewritten(GsurfView *view, const gchar *input)
{
	GsurfModuleManager *mgr = gsurf_module_manager_get_default();
	g_autofree gchar *rewritten = gsurf_module_manager_dispatch_rewrite_uri(mgr, input);

	gsurf_view_load_uri(view, rewritten != NULL ? rewritten : input);
}

/* Locate the module directory: $GSURF_MODULE_PATH, else <exe-dir>/modules
 * (development), else the installed module dir. */
static gchar *
find_module_dir(void)
{
	const gchar *env = g_getenv("GSURF_MODULE_PATH");
	g_autofree gchar *exe = NULL;
	gchar *dir;

	if (env != NULL && g_file_test(env, G_FILE_TEST_IS_DIR))
		return g_strdup(env);

	exe = g_file_read_link("/proc/self/exe", NULL);
	if (exe != NULL) {
		g_autofree gchar *exe_dir = g_path_get_dirname(exe);
		dir = g_build_filename(exe_dir, "modules", NULL);
		if (g_file_test(dir, G_FILE_TEST_IS_DIR))
			return dir;
		g_free(dir);
	}

	if (g_file_test(GSURF_MODULEDIR, G_FILE_TEST_IS_DIR))
		return g_strdup(GSURF_MODULEDIR);

	return NULL;
}

static void
on_view_title_changed(GsurfView *view, const gchar *title, gpointer user_data)
{
	GsurfWindow *window = user_data;
	g_autofree gchar *full = NULL;

	full = g_strdup_printf("%s%sgsurf",
		(title && *title) ? title : "",
		(title && *title) ? " — " : "");
	gsurf_window_set_title(window, full);
}

/* A WebKit popup / target=_blank / window.open request: create a fresh
 * view, add it as a tab, make it active, and return it for the engine to
 * load the popup URI into. Returns %NULL only if no window is available. */
static GsurfView *
on_create_view(GsurfView *source, const gchar *uri, gpointer user_data)
{
	GsurfApplication *app = user_data;
	GsurfWindow *window = gsurf_application_get_active_window(app);

	(void) source;
	(void) uri; /* the engine drives the load into the returned view */

	if (window == NULL)
		return NULL;

	/* make_tab adds + activates the view (wiring its signals via
	 * "view-added") and returns it still owned by the window. */
	return make_tab(window, NULL);
}

/* Wire the host-level signals every view needs, regardless of how it was
 * created (initial view, tab module, or WebKit popup). Invoked from the
 * window's "view-added" signal so it covers all of them uniformly. */
static void
setup_view(GsurfApplication *app, GsurfWindow *window, GsurfView *view)
{
	if (g_object_get_data(G_OBJECT(view), "gsurf-wired") != NULL)
		return;
	g_object_set_data(G_OBJECT(view), "gsurf-wired", GINT_TO_POINTER(1));

	g_signal_connect(view, "title-changed", G_CALLBACK(on_view_title_changed), window);
	g_signal_connect(view, "load-changed", G_CALLBACK(on_view_load_changed), NULL);
	g_signal_connect(view, "create-view", G_CALLBACK(on_create_view), app);
}

static void
on_view_added(GsurfWindow *window, GsurfView *view, gpointer user_data)
{
	setup_view(GSURF_APPLICATION(user_data), window, view);
}

/* Create a new view, apply config settings, add it to the window as a tab
 * and make it active. If @uri is non-NULL, begin loading it (rewritten by
 * URI-handler modules). Returns the view (owned by the window). */
static GsurfView *
make_tab(GsurfWindow *window, const gchar *uri)
{
	GsurfConfig *cfg = gsurf_config_get_default();
	GsurfView *view = gsurf_view_new();

	if (cfg != NULL && cfg->settings != NULL)
		gsurf_view_apply_settings(view, cfg->settings);

	gsurf_window_add_view(window, view);          /* fires "view-added" -> setup_view */
	gsurf_window_set_active_view(window, view);

	if (uri != NULL && *uri != '\0')
		load_uri_rewritten(view, uri);

	g_object_unref(view);                         /* window holds the ref now */
	return view;
}

/* ===== main ===== */

int
main(int argc, char *argv[])
{
	GOptionContext *context;
	GError *error = NULL;
	GsurfConfig *config;
	GsurfApplication *app;
	GsurfWindow *window;
	GsurfView *view;
	const gchar *target_uri;

	context = g_option_context_new("[URI] - GObject Surf web browser");
	g_option_context_add_main_entries(context, entries, NULL);
	if (!g_option_context_parse(context, &argc, &argv, &error)) {
		g_printerr("gsurf: %s\n", error->message);
		g_clear_error(&error);
		g_option_context_free(context);
		return EXIT_FAILURE;
	}
	g_option_context_free(context);

	if (opt_version) {
		g_print("gsurf %s (backend: %s)\n",
			gsurf_get_version_string(), gsurf_backend_get_name());
		return EXIT_SUCCESS;
	}
	if (opt_generate_yaml) {
		g_print("%s", default_yaml_config);
		return EXIT_SUCCESS;
	}
	if (opt_generate_c) {
		g_print("%s", default_c_config);
		return EXIT_SUCCESS;
	}
	if (opt_list_modules) {
		print_module_list();
		return EXIT_SUCCESS;
	}

	gsurf_init(&argc, &argv);

	/* Select the libregnum backend before backend_init so the right backend
	 * is initialised.  Bare --lrg / --lrg=2d only; 3d/3dvr are reserved. */
	if (opt_lrg_given) {
		if (!gsurf_backend_is_available(GSURF_BACKEND_LRG)) {
			g_printerr("gsurf: --lrg requested but this build has no "
				"libregnum backend (build with LRG_BACKEND=1)\n");
			return EXIT_FAILURE;
		}
		if (!gsurf_lrg_render_mode_is_implemented(opt_lrg_mode)) {
			g_printerr("gsurf: --lrg=%s is not yet implemented; "
				"only 2d is supported\n",
				gsurf_lrg_render_mode_to_string(opt_lrg_mode));
			return EXIT_FAILURE;
		}
		gsurf_backend_set_default_type(GSURF_BACKEND_LRG);
	}

	if (!gsurf_backend_init(&argc, &argv, &error)) {
		g_printerr("gsurf: %s\n", error->message);
		g_clear_error(&error);
		return EXIT_FAILURE;
	}

	/* Build configuration: built-in defaults, then YAML overrides. */
	config = gsurf_config_new();
	if (!opt_no_yaml) {
		if (!gsurf_config_load_from_data(config, default_yaml_config, -1, &error)) {
			g_warning("failed to parse built-in default config: %s",
				error ? error->message : "unknown");
			g_clear_error(&error);
		}

		g_autofree gchar *path = opt_config != NULL
			? g_strdup(opt_config)
			: gsurf_config_find_default_path();
		if (path != NULL) {
			if (!gsurf_config_load_from_file(config, path, &error)) {
				g_warning("failed to load config '%s': %s",
					path, error ? error->message : "unknown");
				g_clear_error(&error);
			}
		}
	}
	gsurf_config_set_default(config);

	/* C config (compiled and loaded via crispy; overrides YAML). */
	if (!opt_no_c_config) {
		g_autofree gchar *cpath = opt_c_config != NULL
			? g_strdup(opt_c_config)
			: gsurf_config_compiler_find_default_path();
		if (cpath != NULL) {
			g_autoptr(GError) cerr = NULL;
			GsurfConfigCompiler *cc = gsurf_config_compiler_new(&cerr);
			if (cc != NULL) {
				if (!gsurf_config_compiler_compile_and_load(cc, cpath, &cerr))
					g_warning("C config '%s': %s", cpath,
						cerr ? cerr->message : "failed");
				g_object_unref(cc);
			} else {
				g_warning("C config compiler: %s",
					cerr ? cerr->message : "init failed");
			}
		}
	}

	/* Build the application and the module manager. */
	app = gsurf_application_new(config);

	GsurfModuleManager *mgr = gsurf_module_manager_get_default();
	gsurf_module_manager_set_application(mgr, app);
	gsurf_module_manager_set_config(mgr, config);
	if (!opt_no_modules) {
		/* The binary's policy: $GSURF_MODULE_PATH, else <exe-dir>/modules,
		 * else the installed system dir (first match). Embedders skip this
		 * and set their own search paths via the manager API instead. */
		g_autofree gchar *moddir = find_module_dir();
		if (moddir != NULL) {
			gsurf_module_manager_add_search_path(mgr, moddir);
			gsurf_module_manager_load_modules(mgr);
		}
	}

	/* Window and initial view. */
	window = gsurf_window_new();
	gsurf_window_set_default_size(window, config->window_width, config->window_height);
	gsurf_window_set_title(window, config->window_title);

#ifdef GSURF_HAVE_LRG_BACKEND
	/* Apply the requested render mode to the libregnum window (2D only). */
	if (opt_lrg_given && GSURF_IS_LRG_WINDOW(window))
		gsurf_lrg_window_set_render_mode(GSURF_LRG_WINDOW(window), opt_lrg_mode);
#endif

	/* Host-level window signals. "view-added" wires every view (initial,
	 * tab, or popup) uniformly via setup_view, so connect it before the
	 * first add_view below. */
	g_signal_connect(window, "key-press", G_CALLBACK(on_key_press), app);
	g_signal_connect(window, "button-press", G_CALLBACK(on_button_press), app);
	g_signal_connect(window, "view-added", G_CALLBACK(on_view_added), app);

	view = gsurf_view_new();
	gsurf_view_apply_settings(view, config->settings);
	gsurf_window_add_view(window, view);          /* fires "view-added" -> setup_view */

	if (config->default_zoom != 1.0)
		gsurf_view_set_zoom_level(view, config->default_zoom);

	gsurf_application_add_window(app, window);

	/* Let startup modules (e.g. session restore) know whether a URI was
	 * given on the command line — a CLI URI takes precedence over them. */
	g_object_set_data(G_OBJECT(app), "gsurf-cli-uri",
		(argc > 1) ? (gpointer)argv[1] : NULL);

	/* Activate modules now that the app/window/view exist. */
	gsurf_module_manager_activate_all(mgr);

	/* A module (session restore) may have already populated the views and
	 * flagged startup as handled; otherwise load the CLI URI or homepage. */
	if (argc > 1) {
		load_uri_rewritten(view, argv[1]);
	} else if (g_object_get_data(G_OBJECT(app), "gsurf-startup-handled") == NULL) {
		target_uri = config->homepage;
		load_uri_rewritten(view, target_uri);
	}

	gsurf_window_present(window);
	if (opt_fullscreen || config->fullscreen_on_start)
		gsurf_window_set_fullscreen(window, TRUE);

	/* The application/window/view are owned by the application now. */
	g_object_unref(view);
	g_object_unref(window);
	g_object_unref(config);

	gsurf_application_run(app);
	g_object_unref(app);

	return EXIT_SUCCESS;
}
