/*
 * main.c - GSURF executable entry point
 *
 * Copyright (C) 2026 Zach Podbielniak
 * SPDX-License-Identifier: AGPL-3.0-or-later
 *
 * Thin binary: option parsing, config loading, and the main loop. All
 * browser logic lives in libgsurf so other applications can embed it.
 */

#include "gsurf.h"

#include <gdk/gdk.h>
#include <stdlib.h>
#include <string.h>

/* Embedded default YAML + C config (generated by the build from
 * data/default-config.yaml and data/default-config.c). */
#include "gsurf-default-config.h"

/* ===== CLI options ===== */

static gchar    *opt_config = NULL;
static gchar    *opt_c_config = NULL;
static gboolean  opt_version = FALSE;
static gboolean  opt_no_yaml = FALSE;
static gboolean  opt_no_c_config = FALSE;
static gboolean  opt_no_modules = FALSE;
static gboolean  opt_generate_yaml = FALSE;
static gboolean  opt_generate_c = FALSE;
static gboolean  opt_list_modules = FALSE;
static gboolean  opt_fullscreen = FALSE;

static const GOptionEntry entries[] = {
	{ "config", 'c', 0, G_OPTION_ARG_FILENAME, &opt_config,
	  "Use the specified YAML config file", "PATH" },
	{ "c-config", 0, 0, G_OPTION_ARG_FILENAME, &opt_c_config,
	  "Use the specified C config file", "PATH" },
	{ "no-yaml-config", 0, 0, G_OPTION_ARG_NONE, &opt_no_yaml,
	  "Skip YAML config loading (use built-in defaults)", NULL },
	{ "no-c-config", 0, 0, G_OPTION_ARG_NONE, &opt_no_c_config,
	  "Skip C config compilation and loading", NULL },
	{ "no-modules", 0, 0, G_OPTION_ARG_NONE, &opt_no_modules,
	  "Do not load any modules", NULL },
	{ "generate-yaml-config", 0, 0, G_OPTION_ARG_NONE, &opt_generate_yaml,
	  "Print the default YAML config to stdout and exit", NULL },
	{ "generate-c-config", 0, 0, G_OPTION_ARG_NONE, &opt_generate_c,
	  "Print the default C config to stdout and exit", NULL },
	{ "list-modules", 0, 0, G_OPTION_ARG_NONE, &opt_list_modules,
	  "List available modules and exit", NULL },
	{ "fullscreen", 'f', 0, G_OPTION_ARG_NONE, &opt_fullscreen,
	  "Start in fullscreen", NULL },
	{ "version", 'v', 0, G_OPTION_ARG_NONE, &opt_version,
	  "Show version and exit", NULL },
	{ NULL }
};

/* ===== Built-in module registry (drives --list-modules) ===== */

typedef struct {
	const gchar *name;
	const gchar *description;
} GsurfBuiltinModule;

static const GsurfBuiltinModule builtin_modules[] = {
	{ "search_engines", "Prefix-based search engines with default-engine fallback" },
	{ "chromebar",      "Address bar that falls back to search for non-URI input" },
	{ "history",        "Log visited URIs to a history file (dmenu integration)" },
	{ "homepage",       "Startup/new-view page and go-home keybind" },
	{ "toggles",        "Runtime toggle keybinds for JS, images, TLS, dark mode, etc." },
	{ "adblock",        "Host/pattern-based request blocking (EasyList + hosts files)" },
	{ "cookie_policy",  "Cookie accept policy with an @Aa-style cycle toggle" },
	{ "tabs",           "Tab-bar UI over the view stack with new/close/switch keys" },
	{ "find_bar",       "Find-in-page UI over the engine find controller" },
	{ "modal",          "Vim-like modal input and link hinting (vimium-style 'f')" },
	{ "omnibar",        "Frequency/recency-ranked history completion popup" },
	{ "bookmarks",      "Save and recall bookmarks (dmenu or built-in popup)" },
	{ "externalpipe",   "Pipe page HTML/text/selection to external commands" },
	{ "playexternal",   "Send media/page/link URI to an external player (mpv)" },
	{ "downloads",      "Download manager list UI with progress and notifications" },
	{ "userscripts",    "Inject global and per-domain user JavaScript" },
	{ "site_styles",    "Per-URI user CSS stylesheets (surf styles[])" },
	{ "uri_params",     "Per-domain web engine setting overrides (surf uriparams[])" },
	{ "cert_manager",   "Per-domain certificate exceptions and pinning" },
	{ "useragent",      "Dynamic and per-domain user-agent switching" },
	{ "notifications",  "Desktop notifications (downloads, Web Notifications)" },
	{ "mcp",            "MCP server for AI assistant integration (requires MCP=1)" },
	{ "inspector",      "Toggle the web inspector / devtools" },
	{ "spacesearch",    "Leading space in the bar forces a search" },
	{ "dark_mode",      "Force dark color scheme with optional dark user CSS" },
	{ "status_bar",     "Bottom status bar: URI, load progress, TLS, mode" },
	{ "geolocation",    "Fine-grained geolocation permission policy per-site" },
	{ "session",        "Save and restore open views (tab sessions)" },
	{ "proxy_switch",   "Cycle through proxy presets at runtime" },
	{ NULL, NULL }
};

static void
print_module_list(void)
{
	gint i;

	g_print("Available gsurf modules:\n\n");
	g_print("  %-16s %s\n", "MODULE", "DESCRIPTION");
	g_print("  %-16s %s\n", "------", "-----------");
	for (i = 0; builtin_modules[i].name != NULL; i++)
		g_print("  %-16s %s\n", builtin_modules[i].name,
			builtin_modules[i].description);
	g_print("\nEnable modules under the `modules:` section of your config.yaml.\n");
}

/* ===== Keybinding dispatch ===== */

static void
scroll_js(GsurfView *view, const gchar *js)
{
	gsurf_view_run_javascript_async(view, js, NULL, NULL, NULL);
}

static gboolean
execute_action(GsurfApplication *app, GsurfWindow *window,
               GsurfView *view, GsurfAction action)
{
	if (view == NULL)
		return FALSE;

	switch (action) {
	case GSURF_ACTION_BACK:           gsurf_view_go_back(view); return TRUE;
	case GSURF_ACTION_FORWARD:        gsurf_view_go_forward(view); return TRUE;
	case GSURF_ACTION_RELOAD:         gsurf_view_reload(view, FALSE); return TRUE;
	case GSURF_ACTION_RELOAD_NOCACHE: gsurf_view_reload(view, TRUE); return TRUE;
	case GSURF_ACTION_STOP:           gsurf_view_stop_loading(view); return TRUE;
	case GSURF_ACTION_ZOOM_IN:
		gsurf_view_set_zoom_level(view, gsurf_view_get_zoom_level(view) + 0.1);
		return TRUE;
	case GSURF_ACTION_ZOOM_OUT:
		gsurf_view_set_zoom_level(view, MAX(0.2, gsurf_view_get_zoom_level(view) - 0.1));
		return TRUE;
	case GSURF_ACTION_ZOOM_RESET:     gsurf_view_set_zoom_level(view, 1.0); return TRUE;
	case GSURF_ACTION_SCROLL_DOWN:    scroll_js(view, "window.scrollBy(0,60)"); return TRUE;
	case GSURF_ACTION_SCROLL_UP:      scroll_js(view, "window.scrollBy(0,-60)"); return TRUE;
	case GSURF_ACTION_SCROLL_LEFT:    scroll_js(view, "window.scrollBy(-60,0)"); return TRUE;
	case GSURF_ACTION_SCROLL_RIGHT:   scroll_js(view, "window.scrollBy(60,0)"); return TRUE;
	case GSURF_ACTION_SCROLL_TOP:     scroll_js(view, "window.scrollTo(0,0)"); return TRUE;
	case GSURF_ACTION_SCROLL_BOTTOM:  scroll_js(view, "window.scrollTo(0,document.body.scrollHeight)"); return TRUE;
	case GSURF_ACTION_PAGE_DOWN:      scroll_js(view, "window.scrollBy(0,window.innerHeight*0.9)"); return TRUE;
	case GSURF_ACTION_PAGE_UP:        scroll_js(view, "window.scrollBy(0,-window.innerHeight*0.9)"); return TRUE;
	case GSURF_ACTION_TOGGLE_FULLSCREEN:
		gsurf_window_set_fullscreen(window, !gsurf_window_get_fullscreen(window));
		return TRUE;
	case GSURF_ACTION_QUIT:           gsurf_application_quit(app); return TRUE;
	default:                          return FALSE;
	}
}

static gboolean
on_key_press(GsurfWindow *window, guint keyval, guint keycode, guint state,
             gpointer user_data)
{
	GsurfApplication *app = user_data;
	GsurfConfig *config = gsurf_application_get_config(app);
	GsurfModuleManager *mgr = gsurf_module_manager_get_default();
	GsurfView *view = gsurf_window_get_active_view(window);
	g_autofree gchar *keystr = NULL;
	GsurfAction action;

	/* Modules (modal keymap, hints, tabs) get first crack. */
	if (gsurf_module_manager_dispatch_key_event(mgr, view, keyval, keycode,
			state, GSURF_MODE_NORMAL))
		return TRUE;

	keystr = gsurf_keys_to_string(keyval, state);
	if (keystr == NULL)
		return FALSE;

	action = gsurf_config_get_keybind_action(config, keystr);
	if (action == GSURF_ACTION_NONE)
		return FALSE;

	return execute_action(app, window, view, action);
}

static void
on_view_load_changed(GsurfView *view, GsurfLoadEvent event, gpointer user_data)
{
	GsurfModuleManager *mgr = gsurf_module_manager_get_default();

	gsurf_module_manager_dispatch_load_changed(mgr, view, event);
	if (event == GSURF_LOAD_COMMITTED)
		gsurf_module_manager_dispatch_after_navigate(mgr, view,
			gsurf_view_get_uri(view));
}

/* Load a URI, first giving URI-handler modules (search engines, etc.) a
 * chance to rewrite the input. */
static void
load_uri_rewritten(GsurfView *view, const gchar *input)
{
	GsurfModuleManager *mgr = gsurf_module_manager_get_default();
	g_autofree gchar *rewritten = gsurf_module_manager_dispatch_rewrite_uri(mgr, input);

	gsurf_view_load_uri(view, rewritten != NULL ? rewritten : input);
}

/* Locate the module directory: $GSURF_MODULE_PATH, else <exe-dir>/modules
 * (development), else the installed module dir. */
static gchar *
find_module_dir(void)
{
	const gchar *env = g_getenv("GSURF_MODULE_PATH");
	g_autofree gchar *exe = NULL;
	gchar *dir;

	if (env != NULL && g_file_test(env, G_FILE_TEST_IS_DIR))
		return g_strdup(env);

	exe = g_file_read_link("/proc/self/exe", NULL);
	if (exe != NULL) {
		g_autofree gchar *exe_dir = g_path_get_dirname(exe);
		dir = g_build_filename(exe_dir, "modules", NULL);
		if (g_file_test(dir, G_FILE_TEST_IS_DIR))
			return dir;
		g_free(dir);
	}

	if (g_file_test(GSURF_MODULEDIR, G_FILE_TEST_IS_DIR))
		return g_strdup(GSURF_MODULEDIR);

	return NULL;
}

static void
on_view_title_changed(GsurfView *view, const gchar *title, gpointer user_data)
{
	GsurfWindow *window = user_data;
	g_autofree gchar *full = NULL;

	full = g_strdup_printf("%s%sgsurf",
		(title && *title) ? title : "",
		(title && *title) ? " — " : "");
	gsurf_window_set_title(window, full);
}

/* ===== main ===== */

int
main(int argc, char *argv[])
{
	GOptionContext *context;
	GError *error = NULL;
	GsurfConfig *config;
	GsurfApplication *app;
	GsurfWindow *window;
	GsurfView *view;
	const gchar *target_uri;

	context = g_option_context_new("[URI] - GObject Surf web browser");
	g_option_context_add_main_entries(context, entries, NULL);
	if (!g_option_context_parse(context, &argc, &argv, &error)) {
		g_printerr("gsurf: %s\n", error->message);
		g_clear_error(&error);
		g_option_context_free(context);
		return EXIT_FAILURE;
	}
	g_option_context_free(context);

	if (opt_version) {
		g_print("gsurf %s (backend: %s)\n",
			gsurf_get_version_string(), gsurf_backend_get_name());
		return EXIT_SUCCESS;
	}
	if (opt_generate_yaml) {
		g_print("%s", default_yaml_config);
		return EXIT_SUCCESS;
	}
	if (opt_generate_c) {
		g_print("%s", default_c_config);
		return EXIT_SUCCESS;
	}
	if (opt_list_modules) {
		print_module_list();
		return EXIT_SUCCESS;
	}

	gsurf_init(&argc, &argv);

	if (!gsurf_backend_init(&argc, &argv, &error)) {
		g_printerr("gsurf: %s\n", error->message);
		g_clear_error(&error);
		return EXIT_FAILURE;
	}

	/* Build configuration: built-in defaults, then YAML overrides. */
	config = gsurf_config_new();
	if (!opt_no_yaml) {
		if (!gsurf_config_load_from_data(config, default_yaml_config, -1, &error)) {
			g_warning("failed to parse built-in default config: %s",
				error ? error->message : "unknown");
			g_clear_error(&error);
		}

		g_autofree gchar *path = opt_config != NULL
			? g_strdup(opt_config)
			: gsurf_config_find_default_path();
		if (path != NULL) {
			if (!gsurf_config_load_from_file(config, path, &error)) {
				g_warning("failed to load config '%s': %s",
					path, error ? error->message : "unknown");
				g_clear_error(&error);
			}
		}
	}
	gsurf_config_set_default(config);

	/* C config (compiled and loaded via crispy; overrides YAML). */
	if (!opt_no_c_config) {
		g_autofree gchar *cpath = opt_c_config != NULL
			? g_strdup(opt_c_config)
			: gsurf_config_compiler_find_default_path();
		if (cpath != NULL) {
			g_autoptr(GError) cerr = NULL;
			GsurfConfigCompiler *cc = gsurf_config_compiler_new(&cerr);
			if (cc != NULL) {
				if (!gsurf_config_compiler_compile_and_load(cc, cpath, &cerr))
					g_warning("C config '%s': %s", cpath,
						cerr ? cerr->message : "failed");
				g_object_unref(cc);
			} else {
				g_warning("C config compiler: %s",
					cerr ? cerr->message : "init failed");
			}
		}
	}

	/* Build the application and the module manager. */
	app = gsurf_application_new(config);

	GsurfModuleManager *mgr = gsurf_module_manager_get_default();
	gsurf_module_manager_set_application(mgr, app);
	gsurf_module_manager_set_config(mgr, config);
	if (!opt_no_modules) {
		g_autofree gchar *moddir = find_module_dir();
		if (moddir != NULL)
			gsurf_module_manager_load_from_directory(mgr, moddir);
	}

	/* Window and initial view. */
	window = gsurf_window_new();
	gsurf_window_set_default_size(window, config->window_width, config->window_height);
	gsurf_window_set_title(window, config->window_title);

	view = gsurf_view_new();
	gsurf_view_apply_settings(view, config->settings);
	gsurf_window_add_view(window, view);

	if (config->default_zoom != 1.0)
		gsurf_view_set_zoom_level(view, config->default_zoom);

	g_signal_connect(window, "key-press", G_CALLBACK(on_key_press), app);
	g_signal_connect(view, "title-changed", G_CALLBACK(on_view_title_changed), window);
	g_signal_connect(view, "load-changed", G_CALLBACK(on_view_load_changed), NULL);

	gsurf_application_add_window(app, window);

	/* Activate modules now that the app/window/view exist. */
	gsurf_module_manager_activate_all(mgr);

	target_uri = (argc > 1) ? argv[1] : config->homepage;
	load_uri_rewritten(view, target_uri);

	gsurf_window_present(window);
	if (opt_fullscreen || config->fullscreen_on_start)
		gsurf_window_set_fullscreen(window, TRUE);

	/* The application/window/view are owned by the application now. */
	g_object_unref(view);
	g_object_unref(window);
	g_object_unref(config);

	gsurf_application_run(app);
	g_object_unref(app);

	return EXIT_SUCCESS;
}
